### ISSUE TITLE
Ethernet 

### ISSUE THREAD

**Issue by richardeoin** [stm32-rs/stm32h7xx-hal#130]
- [ ] ETH_MACMIIAR_CR is only valid for HCLK 150-250 MHz
- [ ] MDIO interface only supports PHYs with address 0 - #130 
- [ ] Add documentation explaining how to use PHY feature flags - #130 
- [ ] Add ethernet to CI - #130 

See also https://github.com/stm32-rs/stm32h7xx-hal/pull/121

**Comment by richardeoin** [comment]
Closed by #152
